[commands."uname -s"]
stdout = "Linux"

[commands."uname -m"]
stdout = "x86_64"

[commands."uname -r"]
stdout = "4.9.87-linuxkit-aufs"

[files."/etc/redhat-release"]
content = "Scientific Linux CERN SLC release 6.9 (Carbon)"