---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/opcua/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/arista/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/atlassian/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/okta/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/ms365/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/google-workspace/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/equinix/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/vsphere/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/gitlab/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/gcp/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/ipmi/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/github/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/vcd/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/azure/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/terraform/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/slack/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/oci/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/aws/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/k8s/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /providers/cloudformation/
    schedule:
      interval: daily
    groups:
      gomodupdates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
