# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

# See https://prometheus.io/docs/prometheus/latest/configuration/configuration/ for configuration options
global:
  scrape_interval: 3s
  external_labels:
    app: $APP_NAME
    version: $VERSION
    build: $BUILD

scrape_configs:
  - job_name: 'mql'
    static_configs:
      - targets: ['localhost:2112']

