---
name: Spell Checking

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  spelling:
    name: Run spell check
    permissions:
      contents: read
      pull-requests: read
      actions: read
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    steps:
      - name: check-spelling
        id: spelling
        uses: check-spelling/check-spelling@v0.0.21
        with:
          suppress_push_for_open_pull_request: 1
          checkout: true
          post_comment: 0
          dictionary_source_prefixes: '{"mondoo": "https://raw.githubusercontent.com/mondoohq/spellcheck-dictionary/main/", "cspell": "https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20220816/dictionaries/"}'
          extra_dictionaries:
            cspell:aws/aws.txt
            cspell:filetypes/filetypes.txt
            cspell:software-terms/src/software-terms.txt
            cspell:software-terms/src/software-tools.txt
            cspell:companies/src/companies.txt
            mondoo:mondoo_dictionary.txt

  comment:
    name: Report
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      contents: write
      pull-requests: write
    if: (success() || failure()) && needs.spelling.outputs.followup
    steps:
      - name: comment
        uses: check-spelling/check-spelling@v0.0.20
        with:
          checkout: true
          task: ${{ needs.spelling.outputs.followup }}
